### ISSUE TITLE
No Entities

### ISSUE THREAD

**Issue by RemiKok63** [TimSoethout/goodwe-sems-home-assistant#79]
I tried to implement the sems portal integration, but it doesn't show any entities. Error is can't fetch data. I checked id and login they are right.

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.sems.sems_api
Source: custom_components/sems/sems_api.py:123 
Integration: GoodWe SEMS API (documentation, issues) 
First occurred: 3 januari 2023 om 15:07:31 (2 occurrences) 
Last logged: 15:28:59

Unable to fetch data from SEMS.

And second

Logger: homeassistant.components.sensor
Source: helpers/update_coordinator.py:197 
Integration: Sensor (documentation, issues) 
First occurred: 3 januari 2023 om 15:07:31 (2 occurrences) 
Last logged: 15:28:59

Error while setting up sems platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/sems/sensor.py", line 57, in async_update_data
    inverters = result["inverter"]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/sems/sensor.py", line 97, in async_update_data
    raise UpdateFailed(f"Error communicating with API: {err}")
homeassistant.helpers.update_coordinator.UpdateFailed: Error communicating with API: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/sems/sensor.py", line 118, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 197, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Error communicating with API: 'NoneType' object is not subscriptable

**Comment by RemiKok63** [comment]
Used the main account, problem solved. Seems not working with visitor account

**Comment by Spyky** [comment]
Hello,
i'm new to homeassistant and want to add Goodwe sems. 1 only see 2 entities. The reame says you can add more.
In which file i have to add that?

**Comment by TimSoethout** [comment]
Hi @Spyky , in your configuration.yaml. please see the home assistant documentation on template sensors.

Closing this since original issue of original poster was already solved.
